[package]
name = "tfx-transfer_spl_token"
version = "0.1.0"
authors = ["Tung Nguyen"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
anchor-lang = "0.7.0"

[features]
cpi = ["no-entrypoint"]
no-entrypoint = []

[lib]
name = "transfer_spl_token"
crate-type = ["cdylib", "lib"]
